# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push

jobs:
  build:
    name: Test nxt_gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true
        python-version: "3.10"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run Ruff Check (Linting)
      run: uv run ruff check .

    - name: Run Ruff Format (Check formatting)
      run: |
        uv run ruff format --check .
        uv run ruff check . --select C90 --exit-zero

    - name: Run Tests (Optional but recommended)
      run: uv run coverage run -m pytest

    - name: Covert Test output
      run: uv run coverage lcov -o coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v2
